*** Variables ***
${APP_UPDATE_RGI109_CODE}             xpath=//*[contains(@text,"RGI-109") or contains(@content-desc,"RGI-109")]
${APP_UPDATE_RGI107_CODE}             xpath=//*[contains(@text,"RGI-107") or contains(@content-desc,"RGI-107")]
${APP_UPDATE_MAYBE_LATER_BUTTON}      xpath=//*[@text="Maybe later" or @content-desc="Maybe later"]
${APP_UPDATE_UPDATE_APP_BUTTON}       xpath=//*[@text="Update app" or @content-desc="Update app"]
