*** Variables ***
${LANDING_LANGUAGE_THAI_BUTTON}         xpath=//*[@resource-id="screenLanding_languageSwitch-language-switch-th" or @content-desc="TH"]
${LANDING_LANGUAGE_ENGLISH_BUTTON}      xpath=//*[@resource-id="screenLanding_languageSwitch-language-switch-en" or @content-desc="EN"]
${LANDING_SKIP_BUTTON}                  xpath=//*[@resource-id="screenLanding_skipButton"]
${LANDING_READY_BUTTON}                 xpath=//*[@resource-id="screenLanding_buttonReady"]
${LANDING_TITLE_TEXT}                   xpath=//*[@resource-id="screenLanding_titleText0"]
${LANDING_DESCRIPTION_TEXT}             xpath=//*[@resource-id="screenLanding_descriptionText0"]
${LANDING_INDICATOR}                    xpath=//*[@resource-id="screenLanding_slickBarIndicator"]
