*** Variables ***
${LANDING_LANGUAGE_THAI_BUTTON}       id=screenLanding_languageSwitch-language-switch-th
${LANDING_LANGUAGE_ENGLISH_BUTTON}    id=screenLanding_languageSwitch-language-switch-en
${LANDING_SKIP_BUTTON}                id=screenLanding_skipButton
${LANDING_TITLE_TEXT}                 id=screenLanding_titleText0
${LANDING_DESCRIPTION_TEXT}           id=screenLanding_descriptionText0
${LANDING_INDICATOR}                  id=screenLanding_slickBarIndicator
