*** Variables ***
${MOBILE_OTP_TITLE_TEXT}    xpath=//android.widget.TextView[@resource-id='screenVerifyMobileNumberOTP_textTitle']

${MOBILE_OTP_REF_CODE}      xpath=//android.widget.TextView[contains(@text,"Reference")]

${MOBILE_OTP_INPUT}         xpath=//*[@resource-id="screenVerifyMobileNumberOTP_inputCodeOTP"]
${FIELD_OTP0}               xpath=//android.widget.TextView[@resource-id="input-code-cell-0"]
