*** Variables ***
${MOBILE_OTP_TITLE_TEXT}    xpath=//android.widget.TextView[@resource-id='screenVerifyMobileNumberOTP_textTitle']

${MOBILE_OTP_REF_CODE}      xpath=//android.widget.TextView[contains(@text,"Reference")]

${MOBILE_OTP_INPUT}         xpath=//*[@resource-id="screenVerifyMobileNumberOTP_inputCodeOTP"]
${FIELD_OTP0}               xpath=//android.widget.TextView[@resource-id="input-code-cell-0"]
${FIELD_OTP1}               xpath=//android.widget.TextView[@resource-id="input-code-cell-1"]
${FIELD_OTP2}               xpath=//android.widget.TextView[@resource-id="input-code-cell-2"]
${FIELD_OTP3}               xpath=//android.widget.TextView[@resource-id="input-code-cell-3"]
${FIELD_OTP4}               xpath=//android.widget.TextView[@resource-id="input-code-cell-4"]
${FIELD_OTP5}               xpath=//android.widget.TextView[@resource-id="input-code-cell-5"]
