*** Variables ***
${PRODUCT_SELECTION_TITLE}          id=screenProductSelection_textTitle
${PRODUCT_SELECTION_DESCRIPTION}    id=screenProductSelection_textDescription
${PRODUCT_SELECTION_CHECKBOXES}     xpath=//*[starts-with(@resource-id,"screenProductSelection_flatListCardsCheckBox_")]
${PRODUCT_SELECTION_PRODUCT_NAMES}    xpath=//*[starts-with(@resource-id,"screenProductSelection_flatListCardsTextProductName_")]
${PRODUCT_SELECTION_CONFIRM}        id=screenProductSelection_buttonConfirm
